// AUTO-GENERATED by scripts/generate-map-demo.mjs — do not edit by hand.
// Demo data for the /map timelapse; replaced by the real WebMap pipeline at launch.

export type MapMarkerKind = 'base' | 'poi' | 'boss' | 'trader';

export interface MapLabel {
  name: string;
  /** in-game day the place was named */
  day: number;
  /** base/poi = the two player-pin categories; boss/trader = system layers placed automatically */
  kind: MapMarkerKind;
  /** who pinned it (player pins) or first sighted it (system layers) */
  by: string;
  /** position as a fraction of the map image (0–1) */
  x: number;
  y: number;
}

export const MAP_DEMO_DAYS = 100;
export const MAP_DEMO_REVEALED_PCT = 47;
/** Percent of the world charted at the close of each day (index 0 = day 1). */
export const MAP_DEMO_REVEALED_BY_DAY: number[] = [1,1.8,2.3,2.9,3.7,4.4,4.7,4.8,5.1,5.4,5.5,6,6,6.2,6.5,6.6,7.1,7.4,7.5,8.1,8.5,8.9,9.3,10,10.3,10.8,11.6,12.1,12.6,13.2,13.4,14.1,14.9,15.4,15.8,16.3,17.5,18.2,19.1,19.6,20.7,21.2,21.5,22.1,22.8,23.4,24.8,25.5,26,26.2,27.5,28,28.4,28.5,28.8,29,29.1,29.2,29.8,30.3,30.7,30.7,30.8,30.8,30.9,31.3,31.4,32,32.3,32.8,33,33,33.5,34.9,36.1,37,37.3,37.8,38.6,39,39.6,40.1,40.3,40.4,40.4,40.5,40.7,40.7,40.8,41.1,41.2,41.5,41.8,42.3,43.1,44.2,45.2,46.1,46.2,46.7];
export const MAP_DEMO_LABELS: MapLabel[] = [
  {
    "name": "Midgard",
    "day": 1,
    "kind": "base",
    "by": "the warband",
    "x": 0.5,
    "y": 0.5
  },
  {
    "name": "Juno Beach II",
    "day": 9,
    "kind": "poi",
    "by": "Bjorn",
    "x": 0.5133,
    "y": 0.416
  },
  {
    "name": "Eikthyr's Altar",
    "day": 12,
    "kind": "boss",
    "by": "Astrid",
    "x": 0.4696,
    "y": 0.4377
  },
  {
    "name": "Haldor",
    "day": 22,
    "kind": "trader",
    "by": "Einar",
    "x": 0.4956,
    "y": 0.527
  },
  {
    "name": "Draugheim",
    "day": 31,
    "kind": "base",
    "by": "Astrid",
    "x": 0.3553,
    "y": 0.629
  },
  {
    "name": "The Elder's Altar",
    "day": 44,
    "kind": "boss",
    "by": "Sean",
    "x": 0.4831,
    "y": 0.423
  },
  {
    "name": "The Dark Chapel",
    "day": 50,
    "kind": "poi",
    "by": "Bjorn",
    "x": 0.2856,
    "y": 0.523
  },
  {
    "name": "Benson's Folly",
    "day": 68,
    "kind": "base",
    "by": "Benson",
    "x": 0.4169,
    "y": 0.3835
  },
  {
    "name": "Skald's Rest",
    "day": 86,
    "kind": "poi",
    "by": "Einar",
    "x": 0.2737,
    "y": 0.5123
  }
];
