// AUTO-GENERATED by scripts/generate-map-demo.mjs — do not edit by hand.
// Demo data for the /map timelapse; replaced by the real WebMap pipeline at launch.

export interface MapLabel {
  name: string;
  /** in-game day the place was named */
  day: number;
  /** position as a fraction of the map image (0–1) */
  x: number;
  y: number;
}

export const MAP_DEMO_DAYS = 100;
export const MAP_DEMO_REVEALED_PCT = 47;
export const MAP_DEMO_LABELS: MapLabel[] = [
  {
    "name": "Midgard",
    "day": 1,
    "x": 0.5,
    "y": 0.5
  },
  {
    "name": "Juno Beach II",
    "day": 9,
    "x": 0.5133,
    "y": 0.416
  },
  {
    "name": "Eikthyr's Ring",
    "day": 12,
    "x": 0.4696,
    "y": 0.4377
  },
  {
    "name": "Draugheim",
    "day": 31,
    "x": 0.3553,
    "y": 0.629
  },
  {
    "name": "The Dark Chapel",
    "day": 50,
    "x": 0.2856,
    "y": 0.523
  },
  {
    "name": "Benson's Folly",
    "day": 68,
    "x": 0.4169,
    "y": 0.3835
  },
  {
    "name": "Skald's Rest",
    "day": 86,
    "x": 0.2737,
    "y": 0.5123
  }
];
