// AUTO-GENERATED by scripts/generate-map-demo.mjs — do not edit by hand.
// Demo data for the /map timelapse; replaced by the real WebMap pipeline at launch.

export type MapMarkerKind = 'base' | 'poi' | 'boss' | 'trader';

export interface MapLabel {
  name: string;
  /** in-game day the place was named */
  day: number;
  /** base/poi = the two player-pin categories; boss/trader = system layers placed automatically */
  kind: MapMarkerKind;
  /** who pinned it (player pins) or first sighted it (system layers) */
  by: string;
  /** position as a fraction of the map image (0–1) */
  x: number;
  y: number;
}

export const MAP_DEMO_DAYS = 100;
export const MAP_DEMO_REVEALED_PCT = 47;
export const MAP_DEMO_LABELS: MapLabel[] = [
  {
    "name": "Midgard",
    "day": 1,
    "kind": "base",
    "by": "the warband",
    "x": 0.5,
    "y": 0.5
  },
  {
    "name": "Juno Beach II",
    "day": 9,
    "kind": "poi",
    "by": "Bjorn",
    "x": 0.5133,
    "y": 0.416
  },
  {
    "name": "Eikthyr's Altar",
    "day": 12,
    "kind": "boss",
    "by": "Astrid",
    "x": 0.4696,
    "y": 0.4377
  },
  {
    "name": "Haldor",
    "day": 22,
    "kind": "trader",
    "by": "Einar",
    "x": 0.4956,
    "y": 0.527
  },
  {
    "name": "Draugheim",
    "day": 31,
    "kind": "base",
    "by": "Astrid",
    "x": 0.3553,
    "y": 0.629
  },
  {
    "name": "The Elder's Altar",
    "day": 44,
    "kind": "boss",
    "by": "Sean",
    "x": 0.4831,
    "y": 0.423
  },
  {
    "name": "The Dark Chapel",
    "day": 50,
    "kind": "poi",
    "by": "Bjorn",
    "x": 0.2856,
    "y": 0.523
  },
  {
    "name": "Benson's Folly",
    "day": 68,
    "kind": "base",
    "by": "Benson",
    "x": 0.4169,
    "y": 0.3835
  },
  {
    "name": "Skald's Rest",
    "day": 86,
    "kind": "poi",
    "by": "Einar",
    "x": 0.2737,
    "y": 0.5123
  }
];
